# Generated by Django 3.2.16 on 2023-01-03 20:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20221221_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user',), 'verbose_name': 'рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ('name',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('name',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='author_not_user',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to='recipes.recipes', verbose_name='рецепт'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_inrecipe', to='recipes.ingredients', verbose_name='ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientin_recipe', to='recipes.recipes', verbose_name='рецепт'),
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tags', verbose_name='Список тегов'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введенное занчение не является HEX-кодом цвета.', regex='^#[a-fA-F0-9]{6}$')], verbose_name='Цвет в HEX'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='slug введен неверно. Может состоять из латинских букв, цифр и спецсимвола _', regex='^[-a-zA-Z0-9_]+$')], verbose_name='slug'),
        ),
    ]
